In [33]:
import scipy.io
import numpy as np
from scipy.spatial.distance import pdist, squareform
from scipy.spatial import distance
import torch
from torch import nn
from torch.utils.data import DataLoader

In [34]:
loss_function = nn.L1Loss()

In [35]:
pred = torch.tensor([1,2,3], dtype = torch.float32)
label = torch.tensor([3,4,6], dtype=torch.float32)

In [36]:
pred = pred.view(-1,1)
label = label.view(-1,1)

In [37]:
label 

tensor([[3.],
        [4.],
        [6.]])

In [38]:
loss_function(pred, label)

tensor(2.3333)

In [39]:
((3-1)**2 + (4-2)**2 + 3**2)/3 

5.666666666666667

In [40]:
17/3

5.666666666666667

In [49]:
# With square kernels and equal stride
m = nn.Conv2d(16, 33, 3, stride=2)
# non-square kernels and unequal stride and with padding
m = nn.Conv2d(16, 33, (3, 5), stride=(2, 1), padding=(4, 2))
# non-square kernels and unequal stride and with padding and dilation
m = nn.Conv2d(16, 33, (3, 5), stride=(2, 1), padding=(4, 2), dilation=(3, 1))
input = torch.randn(20, 16, 50, 100)
output = m(input)
output = nn.Flatten()(output)

In [51]:
output.shape 

torch.Size([20, 85800])

In [52]:
matrix = np.random.rand(5,5)

In [53]:
matrix 

array([[0.51195224, 0.62238701, 0.10922757, 0.78677078, 0.15744457],
       [0.14602743, 0.99364256, 0.0256564 , 0.75986469, 0.07675676],
       [0.96345713, 0.77251709, 0.80901709, 0.33102766, 0.6866741 ],
       [0.50586619, 0.96582704, 0.61425859, 0.74289625, 0.67316459],
       [0.65476294, 0.34236738, 0.43728604, 0.19487916, 0.67883397]])

In [54]:
np.rot90(matrix, k=-1)

array([[0.65476294, 0.50586619, 0.96345713, 0.14602743, 0.51195224],
       [0.34236738, 0.96582704, 0.77251709, 0.99364256, 0.62238701],
       [0.43728604, 0.61425859, 0.80901709, 0.0256564 , 0.10922757],
       [0.19487916, 0.74289625, 0.33102766, 0.75986469, 0.78677078],
       [0.67883397, 0.67316459, 0.6866741 , 0.07675676, 0.15744457]])

In [58]:
data = np.random.rand(5,5)
ori = data 
ori_1 = np.rot90(ori, -1)
ori_2 = np.rot90(ori_1, -1)
ori_3 = np.rot90(ori_2, -1)
np.stack((ori, ori_1, ori_2, ori_3), axis = 0)

array([[[0.12113422, 0.43210137, 0.13478618, 0.46230167, 0.92168012],
        [0.31512213, 0.52977993, 0.94160097, 0.83243036, 0.01892994],
        [0.88426369, 0.24095103, 0.59431919, 0.67656999, 0.8374925 ],
        [0.13645448, 0.57520215, 0.24612627, 0.43322305, 0.68006936],
        [0.6461141 , 0.10205445, 0.51929374, 0.98770688, 0.7783806 ]],

       [[0.6461141 , 0.13645448, 0.88426369, 0.31512213, 0.12113422],
        [0.10205445, 0.57520215, 0.24095103, 0.52977993, 0.43210137],
        [0.51929374, 0.24612627, 0.59431919, 0.94160097, 0.13478618],
        [0.98770688, 0.43322305, 0.67656999, 0.83243036, 0.46230167],
        [0.7783806 , 0.68006936, 0.8374925 , 0.01892994, 0.92168012]],

       [[0.7783806 , 0.98770688, 0.51929374, 0.10205445, 0.6461141 ],
        [0.68006936, 0.43322305, 0.24612627, 0.57520215, 0.13645448],
        [0.8374925 , 0.67656999, 0.59431919, 0.24095103, 0.88426369],
        [0.01892994, 0.83243036, 0.94160097, 0.52977993, 0.31512213],
        [0.92168

In [1]:
0.1380 * 2000

276.0

In [66]:
# Giả sử tensor ban đầu là x có kích thước (253, 23, 64)
x = torch.randn(2,2,2)
# print(x)
# Mở rộng tensor thành kích thước (253, 4, 23, 64)
x_expanded = x.unsqueeze(1)  # Thêm một chiều thứ 2 với kích thước 1, trở thành (253, 1, 23, 64)
x_expanded = x_expanded.expand(-1, 4, -1, -1)  # Nhân bản chiều thứ 2 thành 4 lần
y = torch.zeros(2,4,2,2)
print(y)
print(x_expanded)
torch.concat((y, x_expanded), dim = 3)  # Kết quả sẽ là (253, 4, 23, 64)

tensor([[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]])
tensor([[[[ 0.1182,  1.3212],
          [ 0.4984, -1.0404]],

         [[ 0.1182,  1.3212],
          [ 0.4984, -1.0404]],

         [[ 0.1182,  1.3212],
          [ 0.4984, -1.0404]],

         [[ 0.1182,  1.3212],
          [ 0.4984, -1.0404]]],


        [[[ 0.4061, -0.7494],
          [ 0.5179, -0.7970]],

         [[ 0.4061, -0.7494],
          [ 0.5179, -0.7970]],

         [[ 0.4061, -0.7494],
          [ 0.5179, -0.7970]],

         [[ 0.4061, -0.7494],
          [ 0.5179, -0.7970]]]])


tensor([[[[ 0.0000,  0.0000,  0.1182,  1.3212],
          [ 0.0000,  0.0000,  0.4984, -1.0404]],

         [[ 0.0000,  0.0000,  0.1182,  1.3212],
          [ 0.0000,  0.0000,  0.4984, -1.0404]],

         [[ 0.0000,  0.0000,  0.1182,  1.3212],
          [ 0.0000,  0.0000,  0.4984, -1.0404]],

         [[ 0.0000,  0.0000,  0.1182,  1.3212],
          [ 0.0000,  0.0000,  0.4984, -1.0404]]],


        [[[ 0.0000,  0.0000,  0.4061, -0.7494],
          [ 0.0000,  0.0000,  0.5179, -0.7970]],

         [[ 0.0000,  0.0000,  0.4061, -0.7494],
          [ 0.0000,  0.0000,  0.5179, -0.7970]],

         [[ 0.0000,  0.0000,  0.4061, -0.7494],
          [ 0.0000,  0.0000,  0.5179, -0.7970]],

         [[ 0.0000,  0.0000,  0.4061, -0.7494],
          [ 0.0000,  0.0000,  0.5179, -0.7970]]]])

In [ ]:
x = torch.tensor()